version: '4.27.2'
services:
  api-car:
    image: bitnami/postgresql
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=api-car
    volumes:
      - postgres:/bitnami/postgresql
    ports:
      - '5432:5432'

volumes:
 postgres: